### ISSUE TITLE
Enhancing the Multi-clipboard project

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Awesome-Automations#1]
- [ ] Extend the multiclipboard program in this repository so that it has a ```delete <keyword>``` command line argument that will delete a keyword from the shelf. 
- [ ] Then add a ```delete``` command line argument that will delete all keywords.

**Comment by Whitedevil1206** [comment]
Hello ,I want to solve this issue .

**Comment by Arsenic-ATG** [comment]
@Whitedevil1206 why not, I would be waiting for your pull request

**Comment by Whitedevil1206** [comment]
I have linked the PR please review it !
