### ISSUE TITLE
Readme changes ( + Ideas , + Contribution instructions )

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Awesome-Automations#2]
- [x] add a way to take ideas from the viewers for future projects
- [ ] add contributing instructions

**Comment by Arsenic-ATG** [comment]
there exists a section in readme.md about ideas now , but it would be better if there would be another complete file IDEAS.md which will contain 

1. All the information about posting an ideas
2. A list of current ideas that are being worked upon.

**Comment by vivek80801** [comment]
Can we automate login on github or any platfrom ?

**Comment by Arsenic-ATG** [comment]
@vivek80801 that's a nice idea. Let me see what I can do.

**Comment by vivek80801** [comment]
@Arsenic-ATG  


Can you give me chance to automate github login ?

I don't know python much. So, Can I do with javascript or typescript?

**Comment by Arsenic-ATG** [comment]
@vivek80801 why not. Just create a new issue regarding the same and I will assign you to it.

**Comment by Arsenic-ATG** [comment]
As the entire repository is changing right now(as specified in issue #6 ) so I am closing this issue as readme is going to be changed completely.

Also if you have a new idea ,then you can open a new Issue regarding the same.
