### ISSUE TITLE
Wanted to know that i can add c project 

### ISSUE THREAD

**Issue by UG-SEP** [Arsenic-ATG/Awesome-Automations#35]
Hey,
@Arsenic-ATG I wanted to add my c language project in this can i add  please see the project link 
### Link to the project  
https://github.com/UG-SEP/Paint-with-UG-The-SEP
https://github.com/UG-SEP/Tic-Tac-Toe-AI-Intergrated
https://github.com/UG-SEP/UG-Typing-Expert
```javascript
if(You Want to know what is automatic)
{
I can tell you 
}
```
## If you like this project then please give a star 😅⭐

**Comment by Arsenic-ATG** [comment]
Yes, projects that make everyday task easier are always welcome in this repository. 

there are 2 ways to add this project in the repository : -

1.  Adding just the link of the project on the [Home Readme.md](https://github.com/Arsenic-ATG/Awesome-Automations#some-notable-projects-) file 

2. Adding the entire project in the repository making the project a part of all the automations. ( read [CONTRIBUTING.md](https://github.com/Arsenic-ATG/Awesome-Automations/blob/master/CONTRIBUTING.md) for more details on how to create/add a project to the repo )

I would be waiting for your PR.

**Comment by UG-SEP** [comment]
ok
