### ISSUE TITLE
Interested to work in the Blockchain space?

### ISSUE THREAD

**Issue by rohanagarwal94** [Arsenic-ATG/Awesome-Automations#37]
Hello,
You didn't have a public profile, hence had to open an issue here.

I am Rohan. We at Cypherock are working at the intersection of Blockchain, Embedded, Cryptography, and security on a World's first product. You can read more @ - https://angel.co/company/cypherock-wallet. If this interests you, let me know and we can talk about work together in some capacity. We have C dev roles majorly.

Best,
Rohan
rohan@cypherock.com

**Comment by Arsenic-ATG** [comment]
Hi @rohanagarwal94 , I am fairy new to block chain and cryptography. 

What kind of work are talking about here ?

**Comment by rohanagarwal94** [comment]
Hello,Not knowing Blockchain and Cryptography is not a problem. We have two roles - Low level C dev on Custom hardware with Blockchain, Cryptography and Security into the mix & React Dev on Electron framework based Desktop app with Blockchain, Cryptography and Security into the mix. Let me know what works. You should have great C dev or Js dev skills, rest will be learnt with us.

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 9, 2021 at 19:19, ***@***.***> wrote:   


Hi @rohanagarwal94 , I am fairy new to block chain and cryptography.

What kind of work are talking about here ?

**Comment by vivek80801** [comment]
Wow, first time seeing a job offer on GitHub. @Arsenic-ATG congratulation for job offer.

**Comment by Arsenic-ATG** [comment]
Thanks for contacting me, I will be continuing the discussion via E-mail and closing this issue for now.
