### ISSUE TITLE
fix the typo and link mistake 

### ISSUE THREAD

**Issue by UG-SEP** [Arsenic-ATG/Awesome-Automations#40]
Hey @Arsenic-ATG ,
There is a typo mistake and the link are not in a correct form 
[Click here to see mistake ](https://github.com/Arsenic-ATG/Awesome-Automations/blob/master/Automations/createReadmeFile/README.md)
![mis 1](https://user-images.githubusercontent.com/75884061/115122780-56eba180-9fd7-11eb-85e7-fb019ad4647a.jpg)
![mis 2](https://user-images.githubusercontent.com/75884061/115122782-594dfb80-9fd7-11eb-8f5f-2f455b51fc00.jpg)

**Comment by vivek80801** [comment]
@UG-SEP Thanks for feedback.
