### ISSUE TITLE
Time Converter

### ISSUE THREAD

**Issue by Rellotscrewdriver** [Arsenic-ATG/Awesome-Automations#58]
## Idea 💡: -
How about a time converter? like if we wanna convert from 32 seconds to a Century or a Decade. 
manually, this would take forever converting it from minutes to hours to days, ugh.

### sub-goal or optional challenge: 
the user should be able to type like this `Convert 32 Seconds to Century` and then a message showing that it successfully converted to `1.0147e-8` or close to it.

**Comment by DanWlker** [comment]
Hi can i try this?

**Comment by Arsenic-ATG** [comment]
> Hi can i try this?

Sure go ahead.

**Comment by olaleykhan** [comment]
@Arsenic-ATG can I work on this?

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG can I work on this?

@olaleykhan sorry for late replay. 
feel free to work on any open unassigned issue you want.

If you want, I can also assign you this issue.

**Comment by olaleykhan** [comment]
great. I will work on it. thanks
will hit you up if facing any issues

**Comment by Arsenic-ATG** [comment]
> Hi, considering this issue is still open, can I try?

indeed, just make sure you have read [Contribution guidelines](https://github.com/Arsenic-ATG/Awesome-Automations/blob/master/CONTRIBUTING.md) before.

**Comment by nghi01** [comment]
I've finished the automations using C++. Please let me know if there's any issues.
