### ISSUE TITLE
Add RenPy for Automating File Renaming

### ISSUE THREAD

**Issue by MFM-347** [Arsenic-ATG/Awesome-Automations#96]
## Idea 💡: -

I would like to propose adding a new Python script named RenPy to automate the renaming of files in a specified directory. This script uses the `pyfiglet` library to generate a banner and `argparse` for command-line arguments. It supports renaming files based on alphabetical order, newest-to-oldest, or oldest-to-newest, and includes a simulation mode for previewing changes without making any actual modifications.

**Benefits:**

1. Automates the renaming of files, saving time and effort.
2. Provides flexibility with different ordering options.
3. Includes a simulation mode to preview changes without making any actual modifications.

**Comment by Arsenic-ATG** [comment]
Marking this as done with successful merge of #97 

Thank you again for the contribution
